// electron/src/main/conduit/config.ts
import fs from 'node:fs';
import path from 'node:path';
import { logger } from '../logger';

export interface ConduitConfigOptions {
  port: number;
  serverName: string;
  dataDir: string;
}

export function generateConduitConfig(opts: ConduitConfigOptions): string {
  return `# Auto-generated by AgentPlatform. Do not edit manually.
[global]
server_name = "${opts.serverName}"
database_path = "${opts.dataDir}"
database_backend = "sqlite"
port = ${opts.port}
address = "127.0.0.1"
allow_registration = true
yes_i_am_very_very_sure_i_want_an_open_registration_server_prone_to_abuse = true
`;
}

export async function writeConduitConfig(opts: ConduitConfigOptions): Promise<string> {
  const configPath = path.join(opts.dataDir, 'conduit.toml');
  const toml = generateConduitConfig(opts);
  fs.writeFileSync(configPath, toml, 'utf-8');
  logger.info('Conduit config written', { path: configPath });
  return configPath;
}